### ISSUE TITLE
Manifest V3 Permissions

### ISSUE THREAD

**Issue by lennartschoch** [MartinMouritzen/segment-chromeextension#30]
Hey Martin,

Firstly, thanks for this awesome project, you've really done an amazing job here!

Chrome prompted me today, saying that the extension is asking for additional permissions, namely the browser history and copy and paste permissions.

I saw that you recently migrated to the V3 Manifest and I assume that the permission change happened because of that. I was wondering if there is any way we could bring the extensions back to it's original permissions? I can see how some users (including myself) are a bit worried about this permission change.

**Comment by MartinMouritzen** [comment]
Hi Lennart,
I was under the impression that I would the the "clipboardWrite","tabs" and "activeTab" permissions, but it doesn't seem like I do. I will remove them and push a new release to the web store. I hope that will take care of the permissions. Like you I am only interested in as few permissions as possible :)

**Comment by lennartschoch** [comment]
Amazing @MartinMouritzen, thanks a lot for the quick fix here!🙏 Will close this :)
