### ISSUE TITLE
Add support for page, identify, group, and alias calls.

### ISSUE THREAD

**Issue by bbeaird** [MartinMouritzen/segment-chromeextension#9]
Currently, only track calls are tracked via the Chrome extension. Page and identify would be the most important, followed by group and alias. I'll try to do this in the future...

**Comment by MartinMouritzen** [comment]
This seems like a great idea. If you don't look into it, let me know, and I will look into it in the future.

**Comment by MartinMouritzen** [comment]
@bbeaird I've added support for Page and Identify events :)
